# Generated by Django 4.0.1 on 2022-01-23 10:45

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='booksDB',
            fields=[
                ('title', models.CharField(max_length=200)),
                ('author', models.CharField(max_length=5)),
                ('publish_date', models.CharField(max_length=10)),
                ('isbn', models.CharField(blank=True, max_length=200, null=True)),
                ('book_id', models.AutoField(primary_key=True, serialize=False)),
            ],
        ),
    ]
