# Generated by Django 4.0.1 on 2022-01-23 11:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('libraryApp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='booksdb',
            name='image',
            field=models.ImageField(null=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='booksdb',
            name='author',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='booksdb',
            name='isbn',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='booksdb',
            name='publish_date',
            field=models.DateTimeField(),
        ),
    ]
