# Generated by Django 4.0.1 on 2022-01-24 03:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('libraryApp', '0002_booksdb_image_alter_booksdb_author_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='booksdb',
            name='status',
            field=models.CharField(default=0.000539786784220233, max_length=200),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='booksdb',
            name='image',
            field=models.ImageField(upload_to=None),
        ),
        migrations.CreateModel(
            name='request',
            fields=[
                ('tupc_id', models.IntegerField(primary_key=True, serialize=False)),
                ('student_name', models.CharField(max_length=200)),
                ('email', models.EmailField(max_length=200)),
                ('date_requested', models.DateTimeField()),
                ('book_info', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='libraryApp.booksdb')),
            ],
        ),
    ]
